export const GETPRODUCTS='GETPRODUCTS'
export const ADDPRODUCT='ADDPRODUCT'
export const EDITPRODUCT='EDITPRODUCT'
export const DELETEPRODUCT='DELETEPRODUCT'
export const GETONEPRODUCT="GETONEPRODUCT"